config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  root 'jobs#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :find_job, only: [:show, :edit, :update, :destroy]

	def index
		if params[:category].blank?
			@jobs = Job.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@jobs = Job.where(category_id: @category_id).order("created_at DESC")
		end
	end

	def show
	end

	def new
		@job = Job.new
	end

	def create
		@job = Job.new(jobs_params)

		if @job.save
			redirect_to @job
		else
			render "New"
		end
	end

	def edit
	end

	def update
		if @job.update(jobs_params)
			redirect_to @job
		else
			render "Edit"
		end
	end

	def destroy
		@job.destroy
		redirect_to root_path
	end

	private

	def jobs_params
		params.require(:job).permit(:title, :description, :company, :url, :category_id)
	end

	def find_job
		@job = Job.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= simple_form_for(@job, html: { class: 'form-horizontal'}) do |f|
	= f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a Category" }, input_html: { class: "dropdown-toggle"}
	= f.input :title, label: "Job Title", input_html: { class: "form-control" }
	= f.input :description, label: "Job Description", input_html: { class: "form-control" }
	= f.input :company, label: "Your company", input_html: { class: "form-control" }
	= f.input :url, label: "Link to Job", input_html: { class: "form-control" }
	
	%br/
	= f.button :submit

app/views/jobs/edit.html.haml
%h1 Edit Job

= render 'form'

= link_to "Back", root_path

app/views/jobs/index.html.haml
#jobs
	- @jobs.each do |job|
		.job
			%h2= link_to job.title, job
			%p= job.company

app/views/jobs/new.html.haml
%h1 New Job

= render 'form'

= link_to "Back", root_path

app/views/jobs/show.html.haml
#jobs
	.job
		%h2= @job.title
		%p= @job.description
		%p= @job.company
		%button.btn.btn-default= link_to "Apply for Job", @job.url

#links
	= link_to "Back", root_path, class: "btn btn-sm btn-default"
	= link_to "Edit", edit_job_path(@job), class: "btn btn-sm btn-default"
	= link_to "Delete", job_path(@job), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-default"

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Ruby on Rails Jobs
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand Rails Jobs
			%ul.nav.navbar-nav
				%li= link_to "All Jobs", root_path
				- Category.all.each do |category|
					%li= link_to category.name, jobs_path(category: category.name)
			= link_to "New Job", new_job_path, class: "navbar-text navbar-right navbar-link"
	.container
		.col-md-6.col-md-offset-3
			= yield